version: '2.4'
services:
  waku:
    image: statusteam/nim-waku:v0.19.0
    command: |
      --store:true
      --filter:true
      --lightpush:true
      --websocket-support:true
      --nodekey:7b8d9a670aae6421500b7b3f933d0b5d08b51fcf0f0c2f14cba3a4737c83a228
    ports:
      - 8000:8000/tcp
